{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-gateway-helm.serviceAccountName" . }}
  labels:
    {{- include "ai-gateway-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ai-gateway-helm.serviceAccountName" . }}
rules:
  ###################### TODO: these are needed to create extproc resources, but too strict. Users should restrict these.
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
  ######################
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - aigateway.envoyproxy.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - gateway.envoyproxy.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - list
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ai-gateway-helm.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ai-gateway-helm.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ai-gateway-helm.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
{{- end }}
