apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-gateway-helm.fullname" . }}
  labels:
    {{- include "ai-gateway-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "ai-gateway-helm.selectorLabels" . | nindent 4 }}
