name: Trivy

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '55 17 * * 5'

permissions:
  contents: read

jobs:
  image-scan:
    permissions:
      contents: read  # Required for actions/checkout to fetch code
    name: Image Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to use a stable tagged version

      - name: Build Docker image
        run: |
          IMAGE=envoy-proxy/ai-gateway-dev TAG=${{ github.sha }} make image

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.29.0
        with:
          image-ref: envoy-proxy/ai-gateway-dev:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          exit-code: '1'  # Fail workflow on detected vulnerabilities
          ignore-unfixed: true  # Ignore unfixed vulnerabilities
