name: Trivy

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '55 17 * * 5'

permissions:
  contents: read

jobs:
  image-scan:
    permissions:
      contents: read  # Required for actions/checkout to fetch code
    name: Image Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to use a stable tagged version

      - name: Build Docker image
        run: |
          make docker-build.controller TAG=${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: krishanx92/controller:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          exit-code: '1'  # Fail workflow on detected vulnerabilities
          ignore-unfixed: true  # Ignore unfixed vulnerabilities
